fpga0:
  motor_polynomial_parameters_force2displacement:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
  motor_polynomial_parameters_displacement2force:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
fpga1:
  motor_polynomial_parameters_force2displacement:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
  motor_polynomial_parameters_displacement2force:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
fpga2:
  motor_polynomial_parameters_displacement2force:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
  motor_polynomial_parameters_force2displacement:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
fpga3:
  motor_polynomial_parameters_displacement2force:
    - [0, 21.13302, 0.1157684]
    - [1, -1.663168, 0.1939335]
    - [2, 13.55907, 0.1839197]
    - [3, 29.01621, 0.1956852]
    - [4, 46.56446, 0.191706]
    - [5, 21.70997, 0.2057945]
    - [6, 29.3205, 0.205985]
    - [7, 16.43567, 0.1950537]
    - [8, 30.83329, 0.1446367]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15, 15.6451, 0.2468019]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
  motor_polynomial_parameters_force2displacement:
    - [0, -108.1316, 6.750546]
    - [1, 9.333312, 5.130373]
    - [2, -66.94521, 5.278501]
    - [3, -140.4311, 4.979156]
    - [4, -222.3553, 4.948941]
    - [5, -97.53542, 4.71248]
    - [6, -130.356, 4.66109]
    - [7, -80.59324, 5.049232]
    - [8, -131.5665, 5.39323]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15, -58.2062, 3.927222]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
fpga4:
  motor_polynomial_parameters_displacement2force:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]
  motor_polynomial_parameters_force2displacement:
    - [0, 0, 0]
    - [1, 0, 0]
    - [2, 0, 0]
    - [3, 0, 0]
    - [4, 0, 0]
    - [5, 0, 0]
    - [6, 0, 0]
    - [7, 0, 0]
    - [8, 0, 0]
    - [9, 0, 0]
    - [10, 0, 0]
    - [11, 0, 0]
    - [12, 0, 0]
    - [13]
    - [14]
    - [15]
    - [16]
    - [17]
    - [18]
    - [19]
    - [20]